apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml

configurations:
  - namereference.yaml
  - varreference.yaml

images:
  - name: java-grpc-connector-template
    newName: docker.io/niklaushirt/java-grpc-connector-template
    newTag: latest


